[build]
  publish = "ui"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/SenseTalk_Engine.zip"
  [headers.values]
    Content-Type = "application/zip"
    Content-Disposition = "attachment; filename=\"SenseTalk_Engine.zip\""

[[headers]]
  for = "/SenseTalk_Engine_v*.zip"
  [headers.values]
    Content-Type = "application/zip"
    Content-Disposition = "attachment"
    Cache-Control = "public, max-age=3600"

